name: Build and Verify Container
on:
  pull_request:
    branches: [ "main" ]
env:
  GODOT_VERSION: 4.1.3
  RELEASE_NAME: stable

jobs:
  determine_version:
    uses: ./.github/workflows/determine-version.yml

  build_image:
    needs: determine_version
    uses: ./.github/workflows/build-image.yml
    with:
      sem_ver: ${{ needs.determine_version.outputs.sem_ver }}
      godot_version: ${{ env.GODOT_VERSION }}
      releave_name: ${{ env.RELEASE_NAME }}
      release_image: false

  build_projects:
    needs:
      - determine_version
      - build_image
    uses: ./.github/workflows/build-projects.yml
    with:
      sem_ver: ${{ needs.determine_version.outputs.sem_ver }}
      build_image: ${{ needs.build_image.outputs.github_image_name_and_tag }}
