name: Release Container
on:
  push:
    tags:
      - v*
env:
  IMAGE_NAME: godot4-omnibuilder3d
jobs:

  determine_version:
    uses: ./stages/determine-version.yml
  build_image:
    strategy:
      matrix:
        include:
          - godot_version: 4.2
            release_name: stable
          - godot_version: 4.1.3
            release_name: stable
          - godot_version: 4.0.3
            release_name: stable
    needs: determine_version
    uses: ./stages/build-image.yml
    with:
      sem_ver: ${{ needs.determine_version.outputs.sem_ver }}
      godot_version: ${{ matrix.godot_version }}
      releave_name: ${{ matrix.release_name }}
      release_image: true